### ISSUE TITLE
关于package.json文件里配置上的一些疑惑？

### ISSUE THREAD

**Issue by kungfuboy** [angular-programming/hello-world#1]
```
"dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "core-js": "~2.4.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "~0.6.26"
  }
```
Angular 1.x的时代，直接`<script>`标签引入就能用了，现在却需要这么多个包才能跑起一个Hello world，但是每个包的作用和功能是什么，完全一头雾水，请问能否简要说明一下呢？谢谢~

**Comment by ghost** [comment]
这些基础内容在书籍《揭秘Angular 2》里基本都有涉及讲解 ~

1. 以 "@angular" 开头的都是Angular2框架源码，这个5个 `@angular/xxx` 基本上每个浏览器运行的Angular2应用必须包含的
 - @angular/core：核心模块，包含变化监测、依赖注入、渲染等核心功能的代码；
 - @angular/common：通用模块，包含一些常用的内置指令的代码；
 - @angular/compiler：编译相关功能；
 - @angular/platform-browser 和 @angular/platform-browser-dynamic 是跟平台相关的，这两个模块支持Angular2应用运行在浏览器里，对应的还有 @angular/platform-server，用于服务器端渲染。
> 另外，Angular2源码以模块形式组织，方便按需引入，如本例不需要路由功能，所以无需引入 @angular/router。更多源码模块可查阅[angular源码](https://github.com/angular/angular)
2. `core-js` 是一个polyfill，Angular2应用的正常运行需要依赖一些高级的语言特性，如 ES6/Promise 等，core-js就是包含很多这些新特性的polyfill，引入core-js 可以使得Angular2应用能够兼容更多的浏览器平台，点击[这里](https://github.com/zloirock/core-js)查看更多。
3. `reflect-metadata` 是Angular2处理装饰器的元数据的工具库，即用来解释代码里常见的`@Component()`、`@Directive()` 等装饰器，这是Angular2在动态编译情景必须引入的一个库，实际上这也是ES7的提案特性。注意 `core-js` 本身已经包含了 `reflect-metadata` 如果已经引入了 `core-js`，`reflect-metadata` 无须再引入。
4. `rxjs` 是解决异步和事件组合问题的一个工具，Angular2 的 http 模块（@angular/http）依赖这个库，不过实际上本例并没有使用到 http 请求，所以这个可以移除掉的，希望了解更多rxjs，点击[这里](https://github.com/lizhonghui/blog/issues/8)。
5. `zone.js` 用来帮助处理浏览器异步事件的工具库，Angular2 的变化检测机制基于这个库实现的，这是必须引入的。

**Comment by kungfuboy** [comment]
嗯，谢谢解答！

**Comment by ghost** [comment]
不客气，欢迎多交流 ~
