### ISSUE TITLE
hello-world变形后的问题？

### ISSUE THREAD

**Issue by kungfuboy** [angular-programming/hello-world#2]
为了更好地理解，自己就折腾了一下，试着把hello world里的代码全部写在一个文件main.ts里
```
import 'core-js';
import 'zone.js';
import 'reflect-metadata';
import {Component, NgModule} from '@angular/core';

import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import {BrowserModule} from '@angular/platform-browser';

@NgModule({
    declarations: [AppComponent],
    imports: [BrowserModule],
    bootstrap: [AppComponent]
})
export class AppModule { }

@Component({
    selector: 'hello-world',
    template: `<h3>okok</h3>`
})
export class AppComponent { }

// 编译启动AppMoule模块
platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .catch(err => console.error(err));
```

webpack 编译并没有报错，但是在浏览器上却报了错

￼
![5245d428-3d17-491d-8c45-49877a10247a](https://cloud.githubusercontent.com/assets/10394818/23133158/1b1c8e0c-f7cb-11e6-8821-0fa44321ca98.png)

![1feb372a-1046-487d-a6fa-a03b4bbfe960](https://cloud.githubusercontent.com/assets/10394818/23132517/d278831a-f7c8-11e6-8e57-2707ad4a49af.png)

此外还有一个问题，webpack打包出来之后，竟然有3M那么大，这个体积显然不正常，应该添加什么配置让它能压缩到正常大小？

**Comment by ghost** [comment]
Hi ~
定义模块和定义组件的顺序调换一下试试
```
@Component({
    selector: 'hello-world',
    template: `<h3>okok</h3>`
})
export class AppComponent { }

@NgModule({
    declarations: [AppComponent],
    imports: [BrowserModule],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by ghost** [comment]
这个Demo里的JS没有经过压缩，另外减少包体方法还有很多的，如AOT编译（本例用的是JIT编译），Tree Shaking等。这里有篇tree-shaking的文章：http://blog.mgechev.com/2016/06/26/tree-shaking-angular2-production-build-rollup-javascript/

**Comment by kungfuboy** [comment]
赞！！懂了！

**Comment by ghost** [comment]
恩，实际开发中尽量保持一个文件只包含一个类 ~
