### ISSUE TITLE
关于部署的问题

### ISSUE THREAD

**Issue by kungfuboy** [angular-programming/hello-world#4]
在以前jquery的时候，前端几乎不分生产环境和开发环境，前端的代码只需要提交到版本库，后续的事情就不用关心了。

但现在不一样，工程化之后有了生产环境和开发环境的区别。

![image](https://cloud.githubusercontent.com/assets/10394818/24694369/2bff7d72-1a14-11e7-9c93-d129256da978.png)

现在一个项目的目录大致是这样，打包后的代码都会放入dist目录里，真正部署的时候，代码是前端工程师打包，但运维往往还是像以前一样，把整个前端项目的文件夹都打包到服务器上，也就是包括dist和src以及各个配置文件：

1. 很遗憾，源码必须提交到版本库，而悲催的是，运维也是从版本库里打包代码的，他很自然地会把所有东西一股脑地打包起来，像src目录和各个配置文件，这些本来是不应该部署到服务器的东西。
2. 如果什么都不做，部署后要正常访问前端的文件，访问路径就必须是/project/dist/index.html，而我希望是/project/index.html，也就是不要dist这一层级。
3. 如果把dist目录里的东西全部提出来，往上提一级，路径确实是可以变成/project/index.html，但代码里的api路径很可能要再做一次修改。

请问，前端这边能做些什么，才能解决以上几个问题呢？希望我表述清楚了……

**Comment by ghost** [comment]
关于工程化，部署这块一些逻辑，webpack都可以帮你完成类似的工作。
有很多不同的插件供选择，例如环境切换，路径替换等。
可以参考中文文档：https://doc.webpack-china.org/
